apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-preload-data-config
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS `users`;
    USE `users`;
    DROP TABLE IF EXISTS `user_details`;
    CREATE TABLE `user_details`(
     `id` int NOT NULL AUTO_INCREMENT,
     `name` varchar(255) NOT NULL,
     `email` varchar(255) NOT NULL,
      PRIMARY KEY (`id`)
    );
    INSERT INTO `user_details`(`name`, `email`) VALUES ('Anant Vardhan', 'anant.vardhan@gmail.com');
    INSERT INTO `user_details`(`name`, `email`) VALUES ('Rohit Pareek', 'rohit.pareek@hotmail.com');
    INSERT INTO `user_details`(`name`, `email`) VALUES ('Tina Devi', 'tina_devi@gmail.com');
    INSERT INTO `user_details`(`name`, `email`) VALUES ('Bonnie Lin', 'bonnie_lin@gmail.com');
    INSERT INTO `user_details`(`name`, `email`) VALUES ('Manish Shah', 'manish_shah@hotmail.com');
    INSERT INTO `user_details`(`name`, `email`) VALUES ('Satish Banger', 'satish_banger@gmail.com');
