apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-store
  labels:
    name: mysql-data-store
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo